### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by mrjoelkemp** [mmacmillan/grunt-jsdox#12]
Would you be open to maintainers of jsdox helping to maintain your awesome Grunt plugin? Myself or @pq would love to help.

**Comment by mrjoelkemp** [comment]
@mmacmillan ping.

**Comment by mmacmillan** [comment]
hi @mrjoelkemp, sure; ive been a bit distracted the last few months, but i have some changes to roll in and upgrades to make these next few days to bring things up to speed...please feel free to shoot me any PR's for proposed changes, etc.  I will handle the other issue you opened as well; thanks!

**Comment by mrjoelkemp** [comment]
Hey @mmacmillan. Thanks for getting back to me. I was hinting at, if you're okay with, adding one (or both) of the maintainers to this repo as official contributors, so that the usage (and spread/growth) of JSDox is not limited by the slower schedule of updates/fixes on grunt-jsdox.

We're totally willing to lend a hand at closing some issues and getting PRs merged in.
