### ISSUE TITLE
Not able to use jsdox due to  "Cannot find module 'lodash' ".

### ISSUE THREAD

**Issue by VikramDave** [mmacmillan/grunt-jsdox#2]
I have following jsdox module defined in my Gruntfile:
# 

jsdox: {
    generate: {
      options: {
        contentsTitle: 'My Project API Documentation',
      },
       src: [  'path/to/files' ],
       dest: 'docs/markdown'
    },
  },
...
 grunt.loadNpmTasks('grunt-jsdox');
grunt.registerTask('default', [ 'jsdox']);
# 

I see following in the Terminal:
# 

grunt jsdox
Loading "jsdox.js" tasks...ERROR

> > Error: Cannot find module 'lodash'
> > Warning: Task "jsdox" not found. Use --force to continue.

Aborted due to warnings.
# 

Please share if there a solution/workaround for this issue?

**Comment by Askelkana** [comment]
Having this exact same problem.

**Comment by Askelkana** [comment]
Was able to fix this by install the missing modules myself. So, in the grunt-jsdox folder, type:

npm install lodash
npm install q

I just checked the package.json file and these modules are listed, so I don't know why they didn't get installed.

**Comment by mmacmillan** [comment]
version bumped, thanks!

**Comment by VikramDave** [comment]
Thanks. The version bump did it for me.
