### ISSUE TITLE
Request to bump the jsdox version.

### ISSUE THREAD

**Issue by VikramDave** [mmacmillan/grunt-jsdox#4]
Hi, 

I am a jsdox newbie. The markdown files generated from my javascript files do not describe the @constructor notation. It looks like the support for @constructor and gfm was added in https://github.com/sutoiku/jsdox/pull/3 commit. Can you please point to the fixed release or/and bump up the version so we can use the latest version of jsdox i.e 0.2.9.  The two related projects are as follows.
-https://github.com/stouf/jsdox (with @constructor and gfm support)
-https://github.com/sutoiku/jsdox 

I tried using this locally but it didn't resolve the issue. My package.json looks like follows.

  "dependencies": {
    "jsdox": ">=0.2.9"
  },
  "engine": "node >= 0.10",
  "devDependencies": {
    "grunt": "^0.4.5",
    "jsdox": "git://github.com/stouf/jsdox.git",
    "grunt-jsdox": "^0.1.4",
    "yuidoc2md": "~0.2.0",
    "grunt-yuidoc2md": "0.2.3"
  }

Kindly let me know if you have any suggestions to correctly generate markdown files describing constructor.

Many thanks.

**Comment by mmacmillan** [comment]
Hi, 0.1.5 has been added, thanks!
