### ISSUE TITLE
Cut a new npm release of grunt-jsdox

### ISSUE THREAD

**Issue by mrjoelkemp** [mmacmillan/grunt-jsdox#7]
Since #6 was merged, can you cut a new release of the plugin please?

**Comment by mmacmillan** [comment]
Sure, caught me in between some changes to the root; i bumped the version, no other changes added other than the PR, yet.

**Comment by mrjoelkemp** [comment]
Thanks!

**Comment by mrjoelkemp** [comment]
Can you npm publish the new version please? Thanks in advance.
